=== WoWs-Builder-Team/DataConverter/DataConverter/JsonData/ModifierSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "ModifiersSchema",
  "description": "List of modifiers",
  "type": "array",
  "items": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "gameLocalizationKey": {
          "type": ["string", "null"]
        },
        "appLocalizationKey": {
          "type": ["string", "null"]
        },
        "unit": {
          "enum": ["NotAssigned", "None", "Kilograms", "Millimeters", "Meters", "Kilometers", "Seconds", "Degrees", "Percent", "Hitpoints", "Knots", "MetersPerSecond", "DegreesPerSecond", "PercentPerSecond", "DamagePerSecond", "ShotsPerMinute", "FiresPerMinute"]
        },
        "affectedProperties": {
          "type": "array",
          "uniqueItems":  true,
          "items":{
            "type": "string",
            "pattern": "\\w+\\.(\\w)?."
          }
        },
        "displayValueProcessingKind": {
          "enum": ["NotAssigned", "Raw", "ToNegative", "ToPositive", "Discard", "ToInt", "RawOrPercentage", "PositivePercentage", "NegativePercentage", "InverseNegativePercentage", "VariablePercentage", "IntVariablePercentage", "DecimalRoundedPercentage", "RoundedPercentage", "BigWorldToKm", "BigWorldToKmDecimal", "MeterToKm"]
        },
        "valueProcessingKind": {
          "enum": ["NotAssigned", "Multiplier", "AddPercentage", "SubtractPercentage", "PositiveMultiplier", "NegativeMultiplier", "RawAdd", "None"]
        }
      },
      "required": [
        "name",
        "gameLocalizationKey",
        "appLocalizationKey",
        "unit",
        "affectedProperties",
        "displayValueProcessingKind",
        "valueProcessingKind"
      ]
    }
}

=== WoWs-Builder-Team/DataConverter/DataConverter/JsonData/Modifiers.json
[
  {
    "name": "AAAuraDamage",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAAURADAMAGE_DESTROYER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "AntiAirDataContainer.ConstantDamage"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AAAuraDamage_AirCarrier",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAAURADAMAGE_AIRCARRIER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "AntiAirDataContainer.ConstantDamage"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AAAuraDamage_Battleship",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAAURADAMAGE_BATTLESHIP",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "AntiAirDataContainer.ConstantDamage"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AAAuraDamage_Cruiser",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAAURADAMAGE_CRUISER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "AntiAirDataContainer.ConstantDamage"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AAAuraDamage_Destroyer",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAAURADAMAGE_DESTROYER",
    "appLocalizationKey": null,
    "unit": "None",
    "affectedProperties": [
      "AntiAirDataContainer.ConstantDamage"
    ],
    "displayValueProcessingKind": "ToInt",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AAAuraDamage_Submarine",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAAURADAMAGE_SUBMARINE",
    "appLocalizationKey": null,
    "unit": "None",
    "affectedProperties": [
      "AntiAirDataContainer.ConstantDamage"
    ],
    "displayValueProcessingKind": "ToInt",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AAAuraReceiveDamageCoeff",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAAURARECEIVEDAMAGECOEFF",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "None"
  },
  {
    "name": "AABubbleDamage",
    "gameLocalizationKey": "PARAMS_MODIFIER_AABUBBLEDAMAGE_DESTROYER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "AntiAirDataContainer.FlakDamage"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AABubbleDamage_AirCarrier",
    "gameLocalizationKey": "PARAMS_MODIFIER_AABUBBLEDAMAGE_AIRCARRIER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "AntiAirDataContainer.FlakDamage"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AABubbleDamage_Battleship",
    "gameLocalizationKey": "PARAMS_MODIFIER_AABUBBLEDAMAGE_BATTLESHIP",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "AntiAirDataContainer.FlakDamage"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AABubbleDamage_Cruiser",
    "gameLocalizationKey": "PARAMS_MODIFIER_AABUBBLEDAMAGE_CRUISER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "AntiAirDataContainer.FlakDamage"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AABubbleDamage_Destroyer",
    "gameLocalizationKey": "PARAMS_MODIFIER_AABUBBLEDAMAGE_DESTROYER",
    "appLocalizationKey": null,
    "unit": "None",
    "affectedProperties": [
      "AntiAirDataContainer.FlakDamage"
    ],
    "displayValueProcessingKind": "ToInt",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AABubbleDamage_Submarine",
    "gameLocalizationKey": "PARAMS_MODIFIER_AABUBBLEDAMAGE_SUBMARINE",
    "appLocalizationKey": null,
    "unit": "None",
    "affectedProperties": [
      "AntiAirDataContainer.FlakDamage"
    ],
    "displayValueProcessingKind": "ToInt",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "AAExtraBubbles",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAEXTRABUBBLES_SKILL",
    "appLocalizationKey": null,
    "unit": "None",
    "affectedProperties": [
      "AntiAirDataContainer.FlakAmount"
    ],
    "displayValueProcessingKind": "ToInt",
    "valueProcessingKind": "RawAdd"
  },
  {
    "name": "AAInnerExtraBubbles",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAINNEREXTRABUBBLES",
    "appLocalizationKey": null,
    "unit": "None",
    "affectedProperties": [
      "AntiAirDataContainer.FlakAmount"
    ],
    "displayValueProcessingKind": "ToInt",
    "valueProcessingKind": "RawAdd"
  },
  {
    "name": "AAMaxHP",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAMAXHP_DESTROYER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [],
    "displayValueProcessingKind": "VariablePercentage",
    "valueProcessingKind": "None"
  },
  {
    "name": "AAMaxHP_AirCarrier",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAMAXHP_AIRCARRIER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [],
    "displayValueProcessingKind": "VariablePercentage",
    "valueProcessingKind": "None"
  },
  {
    "name": "AAMaxHP_Battleship",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAMAXHP_BATTLESHIP",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [],
    "displayValueProcessingKind": "VariablePercentage",
    "valueProcessingKind": "None"
  },
  {
    "name": "AAMaxHP_Cruiser",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAMAXHP_CRUISER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [],
    "displayValueProcessingKind": "VariablePercentage",
    "valueProcessingKind": "None"
  },
  {
    "name": "AAMaxHP_Destroyer",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAMAXHP_DESTROYER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [],
    "displayValueProcessingKind": "VariablePercentage",
    "valueProcessingKind": "None"
  },
  {
    "name": "AAMaxHP_Submarine",
    "gameLocalizationKey": "PARAMS_MODIFIER_AAMAXHP_SUBMARINE",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [],
    "displayValueProcessingKind": "VariablePercentage",
    "valueProcessingKind": "None"
  },
  {
    "name": "activeManeuveringAdditionalConsumables",
    "gameLocalizationKey": "PARAMS_MODIFIER_ACTIVEMANEUVERINGADDITIONALCONSUMABLES",
    "appLocalizationKey": null,
    "unit": "None",
    "affectedProperties": [
      "ConsumableDataContainer.Uses.PCY081"
    ],
    "displayValueProcessingKind": "ToInt",
    "valueProcessingKind": "RawAdd"
  },
  {
    "name": "activeManeuveringReloadCoeff",
    "gameLocalizationKey": "PARAMS_MODIFIER_ACTIVEMANEUVERINGRELOADCOEFF",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "ConsumableDataContainer.Reload.PCY081"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "additionalConsumables",
    "gameLocalizationKey": "PARAMS_MODIFIER_ADDITIONALCONSUMABLES",
    "appLocalizationKey": null,
    "unit": "None",
    "affectedProperties": [
      "ConsumableDataContainer.Uses.Ship"
    ],
    "displayValueProcessingKind": "ToInt",
    "valueProcessingKind": "RawAdd"
  },
  {
    "name": "airDefenseDispReloadCoeff",
    "gameLocalizationKey": "PARAMS_MODIFIER_AIRDEFENSEDISPRELOADCOEFF_MODERNIZATION",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "ConsumableDataContainer.Reload.PCY011"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "airDefenseDispWorkTimeCoeff",
    "gameLocalizationKey": "PARAMS_MODIFIER_AIRDEFENSEDISPWORKTIMECOEFF_MODERNIZATION",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "ConsumableDataContainer.WorkTime.PCY011"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "allConsumableReloadTime",
    "gameLocalizationKey": "PARAMS_MODIFIER_ALLCONSUMABLERELOADTIME",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "ConsumableDataContainer.Reload.Ship",
      "ConsumableDataContainer.PrepTime.PCY048"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "ammoSplashRadiusMultiplier",
    "gameLocalizationKey": "PARAMS_MODIFIER_AMMOSPLASHRADIUSMULTIPLIER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "ShellDataContainer.UnderwaterSplash.Secondary",
      "ShellDataContainer.UnderwaterSplash.Main"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "areaDamageMultiplier",
    "gameLocalizationKey": "PARAMS_MODIFIER_AREADAMAGEMULTIPLIER",
    "appLocalizationKey": null,
    "unit": "Percent",
    "affectedProperties": [
      "AntiAirDataContainer.ConstantDamage"
    ],
    "displayValueProcessingKind": "DecimalRoundedPercentage",
    "valueProcessingKind": "Multiplier"
  },
  {
    "name": "artilleryAlertMinDistance",
    "gameLocalizationKey": null,
    "appLocalizationKey": "IncomingFireAlertDesc",
    "unit": "Kilometers",
    "affectedProperties": [],
    "displayValueProcessingKind": "BigWorldToKm",
    "valueProcessingKind": "None"
  },
  {
